const INT_QUOTES = [
  "The only way to do great work is to love what you do. — Steve Jobs",
  "Live as if you were to die tomorrow. Learn as if you were to live forever. — Gandhi",
  "Education is the most powerful weapon which you can use to change the world. — Mandela",
  "The mind is everything. What you think you become. — Buddha",
  "An investment in knowledge pays the best interest. — Benjamin Franklin",
  "The beautiful thing about learning is that no one can take it away from you. — B.B. King",
  "In the middle of difficulty lies opportunity. — Einstein",
  "The expert in anything was once a beginner. — Helen Hayes",
  "Learning never exhausts the mind. — Leonardo da Vinci",
  "Intellectual growth should commence at birth and cease only at death. — Einstein",
  "The roots of education are bitter, but the fruit is sweet. — Aristotle",
  "Curiosity is the wick in the candle of learning. — William Arthur Ward",
  "Knowledge is power. — Francis Bacon",
  "The more that you read, the more things you will know. — Dr. Seuss",
  "It does not matter how slowly you go as long as you do not stop. — Confucius",
  "Success is the sum of small efforts repeated day in and day out. — Robert Collier",
  "Discipline is the bridge between goals and accomplishment. — Jim Rohn",
  "The only limit to our realization of tomorrow will be our doubts of today. — FDR",
  "What we know is a drop, what we don't know is an ocean. — Isaac Newton",
  "Think deeply. Speak gently. Love much. Laugh often. Work hard. Give freely. Be kind.",
  "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.",
  "Formal education will make you a living; self-education will make you a fortune. — Jim Rohn",
  "I have no special talents. I am only passionately curious. — Einstein",
  "The more I learn, the more I realize how much I don't know. — Einstein",
  "Study hard what interests you the most in the most undisciplined, irreverent way possible. — Feynman",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. — Mandela",
  "You don't have to be great to start, but you have to start to be great. — Zig Ziglar",
  "The secret of getting ahead is getting started. — Mark Twain",
  "Mastery is not something that strikes in an instant, but a gathering power that moves steadily through time.",
  "Practice isn't the thing you do once you're good. It's the thing you do that makes you good.",
];

const CRAFT_QUOTES = [
  "Creativity is intelligence having fun. — Einstein",
  "The creation of something new is not accomplished by the intellect but by the play instinct. — Jung",
  "Simplicity is the ultimate sophistication. — Leonardo da Vinci",
  "The details are not the details. They make the design. — Charles Eames",
  "Have no fear of perfection — you'll never reach it. — Salvador Dali",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Build something 100 people love, not something 1 million people kind of like.",
  "The only way to learn a new programming language is by writing programs in it. — Kernighan",
  "Measure twice, cut once.",
  "Craft is what we learn to do; art is what we are moved to do. — Janna Malamud Smith",
  "The work of the hands is the apprenticeship of the mind.",
  "Good design is obvious. Great design is transparent. — Joe Sparano",
  "Innovation distinguishes between a leader and a follower. — Steve Jobs",
  "The things I make may be unimportant, but making them is. — Unknown",
  "A craftsman is only as good as his tools. But a master makes any tool work.",
  "Quality means doing it right when no one is looking. — Henry Ford",
  "The joy of making something with your own hands is irreplaceable.",
  "Every expert was once a beginner. Every pro was once an amateur.",
  "Build your skills, and the rest will follow.",
  "The carpenter is not the best who makes more chips than all the rest. — Arthur Guiterman",
  "To create, one must first question everything. — Eileen Gray",
  "Woodworking is a state of mind. — Unknown",
  "A beautiful thing is never perfect. — Egyptian Proverb",
  "Make it work, make it right, make it fast. — Kent Beck",
  "Cooking is like love. It should be entered into with abandon or not at all. — Harriet Van Horne",
  "A garden requires patient labor and attention. Plants do not grow merely to satisfy ambitions.",
  "The desire to create is one of the deepest yearnings of the human soul. — Dieter Uchtdorf",
  "First, solve the problem. Then, write the code. — John Johnson",
  "In every job that must be done, there is an element of fun. — Mary Poppins",
  "The reward of a thing well done is having done it. — Ralph Waldo Emerson",
];

const VITALITY_QUOTES = [
  "Take care of your body. It's the only place you have to live. — Jim Rohn",
  "Health is not valued till sickness comes. — Thomas Fuller",
  "The greatest wealth is health. — Virgil",
  "Strength does not come from physical capacity. It comes from an indomitable will. — Gandhi",
  "Family is not an important thing. It's everything. — Michael J. Fox",
  "To keep the body in good health is a duty. — Buddha",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. — Emerson",
  "The best and most beautiful things in the world cannot be seen or even touched — they must be felt.",
  "It is health that is real wealth and not pieces of gold and silver. — Gandhi",
  "A journey of a thousand miles begins with a single step. — Lao Tzu",
  "Fall seven times, stand up eight. — Japanese Proverb",
  "Perseverance is not a long race; it is many short races one after the other. — Walter Elliot",
  "Our greatest glory is not in never falling, but in rising every time we fall. — Confucius",
  "The human body is the best picture of the human soul. — Ludwig Wittgenstein",
  "Happiness is the highest form of health. — Dalai Lama",
  "The love of a family is life's greatest blessing.",
  "Sleep is the best meditation. — Dalai Lama",
  "Movement is a medicine for creating change in a person's physical, emotional, and mental states.",
  "You can't pour from an empty cup. Take care of yourself first.",
  "The present moment is the only moment available to us, and it is the door to all moments. — Thich Nhat Hanh",
  "Being deeply loved by someone gives you strength. Loving someone deeply gives you courage. — Lao Tzu",
  "Children are our most valuable resource. — Herbert Hoover",
  "A healthy outside starts from the inside. — Robert Urich",
  "Energy and persistence conquer all things. — Benjamin Franklin",
  "Rest when you're weary. Refresh and renew yourself, your body, your mind, your spirit.",
  "The family is one of nature's masterpieces. — George Santayana",
  "Your health is an investment, not an expense.",
  "Physical fitness is the first requisite of happiness. — Joseph Pilates",
  "Time spent with family is worth every second.",
  "Do something today that your future self will thank you for.",
];

const STR_QUOTES = [
  "Strength does not come from winning. Your struggles develop your strengths. — Arnold Schwarzenegger",
  "The last three or four reps is what makes the muscle grow. — Arnold Schwarzenegger",
  "The only bad workout is the one that didn't happen.",
  "Take care of your body. It's the only place you have to live. — Jim Rohn",
  "The pain you feel today will be the strength you feel tomorrow.",
  "No pain, no gain. Shut up and train.",
  "Discipline is doing what needs to be done, even when you don't want to do it.",
  "The body achieves what the mind believes.",
  "Sweat is just fat crying.",
  "The clock is ticking. Are you becoming the person you want to be?",
  "What hurts today makes you stronger tomorrow.",
  "The only person you are destined to become is the person you decide to be. — Emerson",
  "Push yourself, because no one else is going to do it for you.",
  "Success isn't given. It's earned. On the track, on the field, in the gym.",
  "Your body can stand almost anything. It's your mind that you have to convince.",
  "Motivation is what gets you started. Habit is what keeps you going. — Jim Ryun",
  "Strength is the product of struggle.",
  "Champions train, losers complain.",
  "Don't count the days. Make the days count. — Muhammad Ali",
  "The resistance that you fight physically in the gym and the resistance that you fight in life can only build a strong character. — Arnold Schwarzenegger",
  "Once you learn to quit, it becomes a habit. — Vince Lombardi",
  "Dead last finish is greater than did not finish, which trumps did not start.",
  "A one-hour workout is 4% of your day. No excuses.",
  "You miss 100% of the shots you don't take. — Wayne Gretzky",
  "Fall down seven times, stand up eight. — Japanese Proverb",
  "The hardest lift of all is lifting your butt off the couch.",
  "Sore today, strong tomorrow.",
  "If something stands between you and your success, move it. Never be denied.",
  "Energy and persistence conquer all things. — Benjamin Franklin",
  "Physical fitness is the first requisite of happiness. — Joseph Pilates",
];

const ALL_QUOTES: Record<string, string[]> = {
  INT: INT_QUOTES,
  CRAFT: CRAFT_QUOTES,
  VITALITY: VITALITY_QUOTES,
  STR: STR_QUOTES,
};

export function getDailyQuote(category: string): string {
  const pool = ALL_QUOTES[category] ?? INT_QUOTES;
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000);
  return pool[dayOfYear % pool.length];
}
